// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cloudquery/cq-provider-aws/client (interfaces: DMSClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	databasemigrationservice "github.com/aws/aws-sdk-go-v2/service/databasemigrationservice"
	gomock "github.com/golang/mock/gomock"
)

// MockDMSClient is a mock of DMSClient interface.
type MockDMSClient struct {
	ctrl     *gomock.Controller
	recorder *MockDMSClientMockRecorder
}

// MockDMSClientMockRecorder is the mock recorder for MockDMSClient.
type MockDMSClientMockRecorder struct {
	mock *MockDMSClient
}

// NewMockDMSClient creates a new mock instance.
func NewMockDMSClient(ctrl *gomock.Controller) *MockDMSClient {
	mock := &MockDMSClient{ctrl: ctrl}
	mock.recorder = &MockDMSClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDMSClient) EXPECT() *MockDMSClientMockRecorder {
	return m.recorder
}

// DescribeReplicationInstances mocks base method.
func (m *MockDMSClient) DescribeReplicationInstances(arg0 context.Context, arg1 *databasemigrationservice.DescribeReplicationInstancesInput, arg2 ...func(*databasemigrationservice.Options)) (*databasemigrationservice.DescribeReplicationInstancesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeReplicationInstances", varargs...)
	ret0, _ := ret[0].(*databasemigrationservice.DescribeReplicationInstancesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeReplicationInstances indicates an expected call of DescribeReplicationInstances.
func (mr *MockDMSClientMockRecorder) DescribeReplicationInstances(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeReplicationInstances", reflect.TypeOf((*MockDMSClient)(nil).DescribeReplicationInstances), varargs...)
}
